name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: macos-26
    steps:
      - name: Printing greeting
        run: echo "Hello World"
      - name: Printing goodbye
        run: echo "Done - bye!"
